GRANT
  INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
ON
  members,
  accounts
TO
  p2k12_pos;

DROP FUNCTION IF EXISTS p2k12_become_member(INT, INT);
DROP FUNCTION IF EXISTS p2k12_create_member(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS p2k12_insert_member(TEXT, TEXT, TEXT);
